apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - image: payara/kubernetes-frontend
      name: frontend
      ports:
        - containerPort: 80